---
#
# Ansible managed
#
language: python

python:
  - "3.7"

services:
  - docker

env:
  global:
    namespace="robertdebock"
  matrix:
    - image="amazonlinux" tag="1"
    - image="amazonlinux"
    - image="alpine"
    - image="alpine" tag="edge"
    # - namespace="archlinux" image="base"
    - image="debian" tag="unstable"
    - image="debian"
    - image="centos" tag="7"
    - image="redhat" tag="7"
    - image="centos"
    - image="redhat"
    - image="fedora"
    - image="fedora" tag="rawhide"
    - image="opensuse"
    - image="ubuntu"

matrix:
  allow_failures:
    - env: image="alpine" tag="edge"
    - env: image="debian" tag="unstable"
    - env: image="fedora" tag="rawhide"

cache:
  - pip

install:
  - pip install --upgrade pip
  - pip install tox

script:
  - tox --parallel all

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
  slack:
    secure: "VFUXKZ3ZK4S858FeA1ynlaMi2HWx34weehc92wXsqsFnYL2NEdV0KObpAUknmsXTWhem862eP2Vk+vYj61Ut6wK3fS42g8z1xuZhlu9ITG0Sctp7DSH1wq1L331O0v3gzy31D5Wb/blPto0DIkdgjOyLFcM1Rt0HFLekEypv3Bwuqo8I1GXnYjRY9eY8Pkw8qFjRhm/gDjfOCeq8wIj9vBCw5TKFNC+EqU2Ugn5sKICuVclrKmvrWhyAjuJOOdhOQbBVoG1dljZdk2XE2gVzxgYsv0vA0Qc0uZCl/c2QSZKAaaxy8tQiyy44qmeLhlsBRPMRTbi1p7uJNn6ktmbgNl5CN2IhOMoYLnTc/4dZMKWYy6bZgGd7wSD+S3w02sSk1Z/RpAwpvqB7LrZMmPCjvQsytQXQvhWo6lI6CuHSEURTdSv68Po16hgwxsnKbo0mSY6GTZr/hRUh6omooYagV8UmjeDNTU02GoUZwzrCIsQfh/VGZ36xmpTpA47esuVLNZYiUOkGYYv6eB3o/OLZx85syaXF0QEdlgU8NCjiyTN0HCD6Yc+vj4JCmez5KVV9c9+mXsotWDu14MH18+GASb5a5MDYviKC2CmDCeaVL2UC0Z+mOAQ+QK+sqNFkOHdOSQ8UXPq5ti5LS1VYJxv2iQVqv1D20RRe1rOSPRFADBQ="
  email: false
