---
# tasks file for ruby
- name: include distribution specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_distribution }}.yml"
    - "default.yml"
    
- name: install software
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ ruby_packages }}"
